-- BEGIN;
-- -- SELECT *
-- -- FROM properties;
-- -- SELECT *
-- -- FROM profiles;
-- WITH previous_profile AS (SELECT id
--                           FROM profiles
--                           WHERE user_role = '1204'
--                           ORDER BY created_on DESC
--                           LIMIT 1)
-- INSERT
-- INTO properties
-- (id, title, description, property_type, address, bedrooms, bathrooms, square_footage, amenities, pet_policy,
--  availability_dates_jsonb, rent_amount, security_deposit, lease_term, owner_id, contact_name, contact_phone,
--  contact_email, location_point, nearby_locations, photos, floor_plan, created_by, created_on, updated_by, updated_on,
--  sharable_groups)
-- VALUES ('123e4567-e89b-12d3-a456-426655440000', 'Beautiful apartment in downtown',
--         'Spacious and bright apartment located in the heart of downtown', 'Apartment',
--         '123 Main Street, Unit 4B, Anytown, USA', 2, 2, 1200, '{
--     "swimming_pool": true,
--     "gym": true,
--     "balcony": false
--   }', '{
--     "cats_allowed": true,
--     "dogs_allowed": false,
--     "pet_deposit": 500
--   }', '{
--     "start_date": "2023-06-01",
--     "end_date": "2024-06-01"
--   }', 2000.00, 1000.00, 12, (SELECT id FROM previous_profile), 'John Doe', '555-555-5555', 'johndoe@email.com',
--         '(40.7128, -74.0060)', 'Central Park, Empire State Building',
--         ARRAY ['https://example.com/photo1.jpg', 'https://example.com/photo2.jpg'],
--         ARRAY ['https://example.com/floor_plan.pdf'], (SELECT id FROM previous_profile), now(), NULL,
--         NULL, ARRAY [(SELECT id FROM previous_profile)]);
--
-- -- Entry 2
-- WITH previous_profile AS (SELECT id
--                           FROM profiles
--                           WHERE user_role = '7543'
--                           ORDER BY created_on DESC
--                           LIMIT 1)
-- INSERT INTO properties
-- (id, title, description, property_type, address, bedrooms, bathrooms, square_footage, amenities, pet_policy,
--  availability_dates_jsonb, rent_amount, security_deposit, lease_term, owner_id, contact_name, contact_phone,
--  contact_email, location_point, nearby_locations, photos, floor_plan, created_by, created_on, updated_by, updated_on,
--  sharable_groups)
-- VALUES ('223e4567-e89b-12d3-a456-426655440000', 'Cozy Studio Apartment',
--         'Charming studio apartment with great natural lighting', 'Apartment',
--         '456 Elm Street, Unit 2A, Anytown, USA', 1, 1, 600, '{
--     "swimming_pool": false,
--     "gym": false,
--     "balcony": true
--   }', '{
--     "cats_allowed": true,
--     "dogs_allowed": true,
--     "pet_deposit": 200
--   }', '{
--     "start_date": "2023-07-01",
--     "end_date": "2024-06-30"
--   }', 1000.00, 500.00, 12, (SELECT id FROM previous_profile), 'Jane Smith', '555-555-5556', 'janesmith@email.com',
--         '(40.1234, -73.9876)', 'Local Park, Shopping Center',
--         ARRAY ['https://example.com/photo3.jpg', 'https://example.com/photo4.jpg'],
--         ARRAY ['https://example.com/floor_plan2.pdf'], (SELECT id FROM previous_profile), now(), NULL,
--         NULL, ARRAY [(SELECT id FROM previous_profile)]);
--
-- -- Entry 3
-- WITH previous_profile AS (SELECT id
--                           FROM profiles
--                           WHERE user_role = '7543'
--                           ORDER BY created_on DESC
--                           LIMIT 1)
-- INSERT INTO properties
-- (id, title, description, property_type, address, bedrooms, bathrooms, square_footage, amenities, pet_policy,
--  availability_dates_jsonb, rent_amount, security_deposit, lease_term, owner_id, contact_name, contact_phone,
--  contact_email, location_point, nearby_locations, photos, floor_plan, created_by, created_on, updated_by, updated_on,
--  sharable_groups)
-- VALUES ('323e4567-e89b-12d3-a456-426655440000', 'Spacious Family Home',
--         'Large family home with a backyard and plenty of room', 'House',
--         '789 Oak Avenue, Anytown, USA', 4, 3, 2500, '{
--     "swimming_pool": true,
--     "gym": false,
--     "balcony": false
--   }', '{
--     "cats_allowed": false,
--     "dogs_allowed": true,
--     "pet_deposit": 0
--   }', '{
--     "start_date": "2023-08-01",
--     "end_date": "2024-07-31"
--   }', 3000.00, 1500.00, 12, (SELECT id FROM previous_profile), 'Michael Johnson', '555-555-5557',
--         'michaeljohnson@email.com',
--         '(40.5678, -73.5432)', 'Elementary School, Supermarket',
--         ARRAY ['https://example.com/photo5.jpg', 'https://example.com/photo6.jpg'],
--         ARRAY ['https://example.com/floor_plan3.pdf'], (SELECT id FROM previous_profile), now(), NULL,
--         NULL, ARRAY [(SELECT id FROM previous_profile)]);
-- END;
--
-- SELECT * FROM properties;
