import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import SplashMainPage from "../containers/SplashPage/SplashMainPage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Item Climate Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SplashMainPage />
        <p className={styles.description}>
          Revisit us soon, for more updates.
        </p>
        <p className={styles.subscribeText}>
          You can even
          <Link href="/subscribe"> subscribe for updates.</Link>
        </p>
        <p className={styles.subscribeText}>
          Not satisfied yet !? You can also
          <Link href="/feedback"> request features ... </Link>
        </p>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
