import {
  Grid,
  useTheme,
} from '@mui/material'
import { Box } from '@mui/system';

import Head from 'next/head';
import InnerNavigation from '../components/NavBar/InnerNavigation';

const containerRootSx = (theme: any) => ({
  display: 'flex',
  flexDirection: 'row',
  justifyContent: 'flex-start',
  gap: theme.spacing(1),
  margin: theme.spacing(1),
});



export default function Home() {

  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Item Climate Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={containerRootSx}>
        <Box>
          <InnerNavigation />
        </Box>
        <Box> Content</Box>
      </Box>
    </>
  )
}
