BEGIN;

SET ROLE postgres;

REASSIGN OWNED BY climate_admin TO postgres;
REASSIGN OWNED BY climate_user TO postgres;
REASSIGN OWNED BY climate_tester TO postgres;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA climate FROM climate_admin;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA climate FROM climate_user;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA climate FROM climate_tester;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA climate FROM climate_admin;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA climate FROM climate_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA climate FROM climate_tester;

REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA climate FROM climate_admin;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA climate FROM climate_user;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA climate FROM climate_tester;

REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA climate FROM climate_admin;
REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA climate FROM climate_user;
REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA climate FROM climate_tester;

DROP ROLE IF EXISTS climate_user;
DROP ROLE IF EXISTS climate_tester;
DROP ROLE IF EXISTS climate_admin;

CREATE ROLE climate_user LOGIN;
CREATE ROLE climate_tester LOGIN;
CREATE ROLE climate_admin LOGIN BYPASSRLS;

END;
